### ISSUE TITLE
关于运行HistCite Pro 2.1之后出现数据丢失的问题

### ISSUE THREAD

**Issue by ifaceyou123** [leoatchina/Scopus2Histcite#1]
大神你好，
你的代码真的太方便了，不过我在使用过程中还是出现了一个问题，运行HistCite Pro 之后出现下图的问题，数据LCS，GCS 和LCR 统计数量都为零，并且Make Graph 没有相互引用关系。我重复倒了几遍数据，完全按照你在[文献引文分析利器 HistCite 详细使用教程暨 HistCite Pro 首发页面](https://zhuanlan.zhihu.com/p/20902898) 里面所讲的操作了许多次，每次都出现同样的问题。不知道你有没有碰到过这种情况，有什么办法可以解决它。
非常感谢！！
![1](https://user-images.githubusercontent.com/39493524/51640863-fb9be780-1f64-11e9-8ae5-4beb72dabc80.JPG)
![2](https://user-images.githubusercontent.com/39493524/51640929-25550e80-1f65-11e9-8abb-546c7daaf133.JPG)

**Comment by percool** [comment]
我也遇到了相同的问题，不知道怎么解决

**Comment by percool** [comment]
我试了一下这里面自带的ris文件，导出的结果中也没有LCS等统计量

**Comment by lk0709** [comment]
请问一下各位有解决这个问题没有，如果有的话麻烦提供一下解决方案，多谢

**Comment by leoatchina** [comment]
已经修复。

**Comment by leoatchina** [comment]
> 
> 
> 我试了一下这里面自带的ris文件，导出的结果中也没有LCS等统计量

哦，你这个问题应该是scopus中导出的数据没有相关项造成，不过我要查正后再看下代码。
